
var contracts = [
    new WorkExperience("nice",
        "National Institue for Health and Care Excellence",
        "Oct 2014 - March 2015",
        "ASP .NET MVC and Orchard CMS"),
    new WorkExperience("nitecrest",
        "Nitecrest",
        "Aug 2014 - Oct 2014",
        "Data processing solutions in .NET with a web front end"),
    new WorkExperience("uu",
        "Universal Utilities",
        "June 2014 - Aug 2014",
        "ASP .NET web Development"),
    new WorkExperience("webnet",
        "WebNET",
        "Aug 2012 - Sept 2013",
        "Document Management System"),
    new WorkExperience("matrix",
        "Matrix Telematics",
        "Feb 2013 - Mar 2013",
        "Amazon Web Services"),
    new WorkExperience("manheim",
        "Manheim Retail Services",
        "Aug 12 - Feb 13",
        "Enterprise solutions for B2B websites"),
    new WorkExperience("daniel",
        "Daniel Contractors",
        "Jan 12 - July 12",
        "ASP .NET MVC3"),
    new WorkExperience("ai-claims",
        "AI Claims",
        "Nov 2011 - Jan 2012",
        "ASP .NET MVC Web Development"),
    new WorkExperience("cooper",
        "Cooper Software",
        "Dec 10 - Jan 11",
        "ASP .NET Webforms"),
    new WorkExperience("bae",
        "BAE Systems",
        "Jan 10 - June 10",
        "Connected systems, WCF")
];