var perms = [
    new WorkExperience("andrews",
        "Andrews",
        "2010",
        "Dynamics CRM"),
    new WorkExperience("ipl",
        "IPL",
        "06 - 09",
        "Programming"),
    new WorkExperience("renishaw",
        "Renishaw",
        "04 - 06",
        "Graduate training"),
    new WorkExperience("other",
        "Other",
        "Before 2004 finishing university degree",
        "Lambda",
        "Personal Project",
        "Logbook Android")];