var perms = [
    new WorkExperience("wbac",
        "webuyanycar.com",
        "Oct 2015 - present",
        "Service Oriented Architecture, AngularJS, MVC, SQL Server, Typescript"),
    new WorkExperience("andrews",
        "Andrews",
        "2010",
        "Dynamics CRM"),
    new WorkExperience("ipl",
        "IPL",
        "2006 - 2009",
        "Programming"),
    new WorkExperience("renishaw",
        "Renishaw",
        "2004 - 2006",
        "Graduate training"),
    new WorkExperience("other",
        "Other",
        "Before 2004 finishing university degree",
        "Lambda",
        "Personal Project",
        "Logbook Android")];